/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 BLU.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/BLU.glb");
  const { actions } = useAnimations(animations, group);
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    //group.current.rotation.z = - 0.01 - (1 + Math.sin(t / 1.5)) / 10
    // group.current.rotation.x = Math.cos(t / 4) / 5;
    group.current.rotation.y = Math.sin(t / 2) / 1;
    //group.current.position.y = (1 + Math.sin(t / 1.5)) / 20
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="d143d045-dfa4-4c01-a0c8-18a5e7c772c9"
          position={[0, 0.53, 0]}
          rotation={[Math.PI / 2, 0, 2]}
          scale={20.71}
        >
          <group name="Meshes">
            <group name="Layer_1" />
          </group>
        </group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 3]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="p0202"
            geometry={nodes.p0202.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.p0202.skeleton}
          />
          <skinnedMesh
            name="p0211"
            geometry={nodes.p0211.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0211.skeleton}
          />
          <skinnedMesh
            name="p0212"
            geometry={nodes.p0212.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0212.skeleton}
          />
          <skinnedMesh
            name="p0213"
            geometry={nodes.p0213.geometry}
            material={materials.Phong_0D1F0C}
            skeleton={nodes.p0213.skeleton}
          />
          <skinnedMesh
            name="p0223"
            geometry={nodes.p0223.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0223.skeleton}
          />
          <skinnedMesh
            name="p0224"
            geometry={nodes.p0224.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0224.skeleton}
          />
          <skinnedMesh
            name="p0225"
            geometry={nodes.p0225.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0225.skeleton}
          />
          <skinnedMesh
            name="p0226"
            geometry={nodes.p0226.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0226.skeleton}
          />
          <skinnedMesh
            name="p0227"
            geometry={nodes.p0227.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0227.skeleton}
          />
          <skinnedMesh
            name="p0228"
            geometry={nodes.p0228.geometry}
            material={materials.Phong_D3D3D3}
            skeleton={nodes.p0228.skeleton}
          />
          <skinnedMesh
            name="s0142"
            geometry={nodes.s0142.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0142.skeleton}
          />
          <skinnedMesh
            name="s0145"
            geometry={nodes.s0145.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0145.skeleton}
          />
          <skinnedMesh
            name="s0147"
            geometry={nodes.s0147.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0147.skeleton}
          />
          <skinnedMesh
            name="s0152"
            geometry={nodes.s0152.geometry}
            material={materials.Phong_A6BBB9}
            skeleton={nodes.s0152.skeleton}
          />
          <skinnedMesh
            name="s0153"
            geometry={nodes.s0153.geometry}
            material={materials.Phong_A6BBB9}
            skeleton={nodes.s0153.skeleton}
          />
          <skinnedMesh
            name="s0209"
            geometry={nodes.s0209.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0209.skeleton}
          />
          <skinnedMesh
            name="s0222"
            geometry={nodes.s0222.geometry}
            material={materials.Phong_0D1F0C}
            skeleton={nodes.s0222.skeleton}
          />
          <skinnedMesh
            name="s0236"
            geometry={nodes.s0236.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0236.skeleton}
          />
          <skinnedMesh
            name="s0237"
            geometry={nodes.s0237.geometry}
            material={materials.Phong_70807E}
            skeleton={nodes.s0237.skeleton}
          />
          <skinnedMesh
            name="s0238"
            geometry={nodes.s0238.geometry}
            material={materials.Phong_0D1F0C}
            skeleton={nodes.s0238.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/BLU.glb");
